### ISSUE TITLE
Blocks/Items checklist for 1.7

### ISSUE THREAD

**Issue by LemADEC** [LemADEC/WarpDrive#45]
Checklist for localization, inventory and world rendering, left/right clicking, no hard crashes:
- [x] Air
- [x] Gas
- [x] Decorative: missing texture will remain
- [x] Iridium block
- [x] Transport beacon: no functional fixes, just rendering/no crash
- [x] Reactor laser focus: no functional fixes, just rendering/no crash
- [x] Air canister
- [x] Armor
- [x] Component
- [x] Upgrade: no functional fixes, just rendering/no crash
- [x] Air generator
- [x] Camera
- [x] Chunkloader: no functional fixes, just rendering/no crash
- [x] Cloaking coil
- [x] Cloaking core
- [x] Laser
- [x] Laser camera
- [x] Laser reactor monitor: no functional fixes, just rendering/no crash
- [x] Laser tree farm: no functional fixes, just rendering/no crash
- [x] Lift
- [x] Mining laser
- [x] Monitor
- [x] Particle booster
- [x] Power laser
- [x] Power reactor
- [x] Power store: no functional fixes, just rendering/no crash
- [x] ShipControler/Protocol
- [x] ShipCore/Reactor
- [x] Ship scanner: no functional fixes, just rendering/no crash
- [x] Transporter
- [x] Warp isolation
- [x] Radar

Checklist for commands:
- [x] Generate ship
- [x] Generate star
- [x] Generate asteroid
- [x] Generate moon
- [x] Generate asteroid field
- [ ] Invisible
- [x] Space
- [ ] Debug

Checklist for functional tests:
- [x] Air propagation
- [x] Gas coloring
- [x] Gravity in space
- [x] Breathing in space
- [x] Camera/LaserCamera/Monitor frequency synchronisation
- [x] Cloaking/uncloaking
- [x] Mining animation, block transfer, power consumption, chunk events
- [x] Particle booster animation
- [x] Reactor cycle
- [x] Reactor explosion
- [x] Jumping short, long, hyper, gate
- [x] Jump blocks drops, entities
- [x] Jump microblocks
- [x] Jump IC2 blocks orientation (not required in SSP, what about SMP?)
- [x] Jump tiles (CC disk, cables, containers, etc.)
- [x] Jump checklist and animation
- [x] Jump collisions
- [x] Radar map
- [x] Isolation counting
- [x] scripts preloading
- [x] dimensions and entities registration
- [x] world generation
- [x] targeting
- [x] laser amplification
- [x] post jump booting

**Comment by LemADEC** [comment]
Invisible and debug are non critical, everything else is fixed, closing
